MvcAndTests
Yanetta/RetailCompany pull request #2
Opened 2019-03-25 10:30 UTC by Yanetta

2019-03-25 11:12 UTC, u2107680007911543774e7r approved these changes
You have postman screenshots committed, but we need .json file collection export from postman

2019-03-25 11:12 UTC, u2107680007911543774e7r commented on pom.xml
> +                            <!--</webResources>-->
we don't push commented old code

2019-03-25 11:12 UTC, saadow commented on src/main/java/workSpringData/controller/Temp.java
> +public class Temp {
this is a test controller, we shouldn't push it

2019-03-25 11:12 UTC, saadow commented on src/main/java/workSpringData/exeption/UpdateException.java
> +package workSpringData.exeption;
package name mistype, should be **exception**

2019-03-25 12:41 UTC, SerhiiPasko requested changes
Read my and Vadim's comments

2019-03-25 12:41 UTC, SergeyPasko commented on src/main/java/workSpringData/controller/CustomersController.java
> +    @GetMapping("/id/{id}")
You can set both of that varians to one request with params such as ?name=value

2019-03-25 12:41 UTC, SergeyPasko commented on src/test/resources/schema.sql
> +CREATE SEQUENCE IF NOT EXISTS CUSTOMERS_SEQ
You don't use this sequnce

2019-03-26 08:40 UTC, SerhiiPasko approved these changes
Good

2019-03-26 17:24 UTC, merged